# --------------------------------
#        My first pipeline
#---------------------------------

name: My-github-actions-laggy-test
env:
  APPLICATION_NAME: "My Flask"
  PACKAGE_NAME    : "My-package-deploy-ver-${{ github.sha }}"
  
# Controls when the workflow will run
on:
  push:
    branches:
      - main
    
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World testing job!"
    - name: Exec few commands
      run : |
        echo "HELLO command 1"
        echo "HELLO command 2"
        echo "Application_name: ${{ env.APPLICATION_NAME}}"
    - name: List current folder
      run : ls -la
    - name: Git clone repo
      uses: actions/checkout@v1
    - name: List current folder
      run : ls -la

      
  
  deploy_jobs:
    runs-on: ubuntu-latest
    env:
      Var1: Job-level_var1
      Var2: Job-level-var2
    needs: testing_job
    steps:
    - name: Print Hello Message
      run : echo "Hello World deploy job!"
    - name: Print VALUE job env
      run: |
        echo: "Print var1=${{env.Var1}}"
        echo: "Print var2=${{env.Var2}}"
      

    - name: Print deploy package
      run : echo "Deploy_package_version:${{ env.PACKAGE_NAME }}"
    - name: Test some package
      run : zip --version
  
    

