# --------------------------------
#        My first pipeline
#---------------------------------

name: My-github-actions-laggy-test

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World testing job!"
  
  deploy_jobs:
    runs-on: ubuntu-latest
    needs: testing_job
    steps:
    - name: Print Hello Message
      run : echo "Hello World deploy job!"
  
    

